<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PQKH3B1" failures="3" tests="4" name="Test" time="0.013" errors="0" timestamp="19 Jun 2020 08:26:04 GMT">
  <testcase classname="test.TestUser" name="test" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.TestUser.test(TestUser.java:11)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase classname="test.TestUser" name="test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.TestUser.test2(TestUser.java:18)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="test.TestUser" name="test3" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.TestUser.test3(TestUser.java:25)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="test.TestUser" name="test4" time="0.0"/>
</testsuite> <!-- Test -->
